apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"9"},"creationTimestamp":"2024-04-21T00:31:51Z","generation":9,"labels":{"app":"currency-conversion"},"name":"currency-conversion","namespace":"default","resourceVersion":"29109466","uid":"e5675eaf-fc5d-475f-afe1-e4bc37391be4"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"currency-conversion"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"currency-conversion"}},"spec":{"containers":[{"image":"elliotcerda95/mmv3-currency-conversion-service:0.0.14-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"mmv3-currency-conversion-service","resources":{"requests":{"memory":"700Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-05-06T22:30:32Z","lastUpdateTime":"2024-05-06T22:30:32Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2024-05-06T22:23:08Z","lastUpdateTime":"2024-05-06T22:39:23Z","message":"ReplicaSet \"currency-conversion-555b4f76d8\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":9,"readyReplicas":1,"replicas":2,"unavailableReplicas":1,"updatedReplicas":1}}
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: elliotcerda95/mmv3-currency-conversion-service:0.0.14-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv3-currency-conversion-service
        resources:
          requests:
            memory: 700Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-06T22:30:32Z"
    lastUpdateTime: "2024-05-06T22:30:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-06T22:23:08Z"
    lastUpdateTime: "2024-05-06T22:50:55Z"
    message: ReplicaSet "currency-conversion-79f489c45f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/neg":"{\"ingress\":true}"},"creationTimestamp":"2024-05-06T21:31:11Z","finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app":"currency-conversion"},"name":"currency-conversion","namespace":"default","resourceVersion":"29074342","uid":"bd19bfd8-83ed-475a-9892-0c8baaadddd6"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.6.104.130","clusterIPs":["10.6.104.130"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":30267,"port":8100,"protocol":"TCP","targetPort":8100}],"selector":{"app":"currency-conversion"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"35.194.23.15"}]}}}
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.6.104.130
  clusterIPs:
    - 10.6.104.130
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30267
      port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 35.194.23.15